# Deploy a Bicep file
# The Bicep file to deploy is called azuredeploy.bicep. The parameter file is called azuredeploy.parameters.json.  Both files exist in the root of the repo.

trigger:
- master
name: 'bicep build and deploy'

variables:
  vmImageName: 'ubuntu-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/'
  geoLocation: '<provide-an-azure-location>'

  azureServiceConnection: '<provide-a-service-connection-name>'
  subscriptionId: '<provide-azure-subscription-id>'
  AZURE_RESOURCE_GROUP: '<provide-a-resource-group-name>'

stages:
- stage: Build
  displayName: Build

  jobs:
  - job: Build
    displayName: Validate and Publish
    pool:
     vmImage: $(vmImageName)

    steps:
      - task: AzureCLI@2
        displayName: Build ARM JSON template from bicep file
        inputs:
          azureSubscription: '$(azureServiceConnection)'
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az --version
            az bicep build --file ./azuredeploy.bicep

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Validate the template'
        inputs:
          azureResourceManagerConnection: '$(azureServiceConnection)'
          subscriptionId: '$(subscriptionId)'
          resourceGroupName: '$(AZURE_RESOURCE_GROUP)'
          location: '$(geoLocation)'
          csmFile: azuredeploy.json
          csmParametersFile: azuredeploy.parameters.json
          deploymentMode: Validation

      - task: CopyFiles@2
        displayName: 'Copy the template'
        inputs:
          TargetFolder: '$(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
          ArtifactName: 'drop'

- stage: Development
  displayName: Deploy to Development
  dependsOn: Build
  condition: succeeded()
  jobs:
    - deployment: Deploy
      displayName: 'Deploying the template'
      environment: 'Development'
      pool:
        vmImage: $(vmImageName)
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureResourceManagerTemplateDeployment@3
                displayName: 'Deploy the template'
                inputs:
                  azureResourceManagerConnection: '$(azureServiceConnection)'
                  subscriptionId: '$(subscriptionId)'
                  resourceGroupName: '$(AZURE_RESOURCE_GROUP)'
                  location: '$(geoLocation)'
                  csmFile: '$(Pipeline.Workspace)/drop/azuredeploy.json'
                  csmParametersFile: '$(Pipeline.Workspace)/drop/azuredeploy.parameters.json'
                  deploymentMode: 'Incremental'